### ISSUE TITLE
Importing the module runs `coloredlogs.install()` which configures the logging for apps using inquirer3

### ISSUE THREAD

**Issue by fbordallo** [guysalt/python-inquirer3#92]
Just by importing this module `import inquirer3` the logging gets configured as it runs `coloredlogs.install()` at `inquirer3.render.console` module.

Importing inquirer3 imports prompt

https://github.com/guysalt/python-inquirer3/blob/992e83f8b8474b0b567de114735b41444ffcaddf/src/inquirer3/prompt.py#L2

which imports render.console

https://github.com/guysalt/python-inquirer3/blob/992e83f8b8474b0b567de114735b41444ffcaddf/src/inquirer3/render/console/__init__.py#L19

and runs `coloredlogs.install()`

Logging should be initialized differently, probably taking into account existing logging config. Or there's probably no need to have colorized logs in this package? Maybe just allow the programs that use inquirer3 decide if they want to use coloredlogs?

I came across this issue by importing pymobiledevice3 which has inquirer3 as a requirement. I was just using some pymobiledevice3 modules and it messed my logger by colorizing the logs and setting the log level to INFO.

Thank you very much for this library.

**Comment by guysalt** [comment]
Hey there! @fbordallo 

I see where the bug is. I will change it soon that the `coloredlogs` will be just for the specific file.

Sorry for the long delay, and thank you for submitting this issue :)

If you encounter any more problems, please let me know!

**Comment by guysalt** [comment]
hey,

version `0.5.0` is out with the fix, decided to remove `coloredlogs` entirely as indeed this is not a package...

closing the issue, thank you
